name: Update Honkai Star Rail Data

on:
  schedule:
    - cron: '0 * * * *' # 1時間に1回自動実行
  workflow_dispatch: # 手動実行用ボタン

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-node: '18'

    - name: Install JSDOM # 解析ライブラリをインストール
      run: npm install jsdom

    - name: Run update script
      env:
        HOYO_LTOKEN: ${{ secrets.HOYO_LTOKEN }}
        HOYO_LTUID: ${{ secrets.HOYO_LTUID }}
        HOYO_UID: ${{ secrets.HOYO_UID }}
      run: node update_data.js

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git diff --cached --quiet || (git commit -m "Auto-update Star Rail stats" && git push)